---  
- name: install-chaos-mesh
  hosts: localhost
  connection: local
  tasks:    
    - name: Add Chaos-Mesh Repo
      register: add_chaos_mesh_result
      shell: "scripts/install_add_chaos_mesh_repo.sh {{ harvester_management_url }}"
    
    - name: Add Chaos-Mesh Repo stdout
      debug:
        msg: "{{ add_chaos_mesh_result.stdout }}"

    - name: Install Chaos-Mesh
      register: install_chaos_mesh_result
      shell: "scripts/install_chaos_mesh.sh {{ harvester_management_url }}"

    - name: Install Chaos-Mesh Repo stdout
      debug:
        msg: "{{ install_chaos_mesh_result.stdout }}"


- name: launch-chaosd
  hosts: harvester
  remote_user: rancher
  become: yes
  become_method: sudo
  become_flags: 'su - root /bin/bash -c'
  tasks:
    - name: copy
      copy:
        src: scripts/install_chaosd.sh
        dest: /tmp/install_chaosd.sh
        mode: 0755

    - name: Launch Chaosd 
      register: launch_chaosd_result
      shell: "/tmp/install_chaosd.sh {{ chaosd_port }}"
        
    - name: debug
      debug:
        msg: "{{ launch_chaosd_result.stdout }}"