---
- name: launch-chaosd
  hosts: "{ harvester_cluster_hosts }"
  remote_user: rancher
  become: yes
  become_method: sudo
  become_flags: 'su - root /bin/bash -c'
  tasks:
    - name: script
      register: script_result
      shell: |
        export CHAOSD_VERSION=v1.4.0

        mkdir -p chaosd
        cd chaosd

        if [ ! -f "$myFile" ]; then
          curl -fsSLO https://mirrors.chaos-mesh.org/chaosd-$CHAOSD_VERSION-linux-amd64.tar.gz
        fi
        
        tar zxvf chaosd-$CHAOSD_VERSION-linux-amd64.tar.gz && sudo mv chaosd-$CHAOSD_VERSION-linux-amd64 /usr/local/
        export PATH=/usr/local/chaosd-$CHAOSD_VERSION-linux-amd64:$PATH
        chaosd server --port {{ chaosd_port }}