---
- name: install-chaos-mesh
  hosts: localhost
  connection: local
  tasks:
    - name: login
      register: login_result
      shell: "scripts/prepare_login.sh {{ harvester_management_url }} {{ harvester_username }} {{ harvester_password }}"           

    - name: login stdout
      debug:
        msg: "{{ login_result.stdout }}"

    - name: Obtain KubeConfig
      register: obtain_kubeconfig_result
      shell: "scripts/prepare_download_kubeconfig.sh {{ harvester_management_url }}"
        

    - name: Obtain KubeConfig stdout
      debug:
        msg: "{{ obtain_kubeconfig_result.stdout }}"