---
- name: uninstall-chaos-mesh
  hosts: localhost
  connection: local
  tasks:
  - name: uninstall chaos-mesh
    register: uninstall_chaos_mesh_result
    shell: |
      helm --kubeconfig kubeconfig.yaml uninstall chaos-mesh -n chaos-testing --wait
      kubectl --kubeconfig kubeconfig.yaml -n chaos-testing delete configmap chaos-mesh
      kubectl --kubeconfig kubeconfig.yaml delete ns chaos-testing