---
- name: uninstall chaosd
  hosts: harvester
  remote_user: rancher
  become: yes
  become_method: sudo
  become_flags: 'su - root /bin/bash -c'
  tasks:
    - name: copy
      copy:
        src: scripts/uninstall_chaosd.sh
        dest: /tmp/uninstall_chaosd.sh
        mode: 0755

    - name: kill chaosd
      register: kill_chaosd_result
      shell: "/tmp/uninstall_chaosd.sh"

- name: uninstall-chaos-mesh
  hosts: localhost
  connection: local
  tasks:
  - name: uninstall chaos-mesh
    register: uninstall_chaos_mesh_result
    shell: "scripts/uninstall_chaos_mesh.sh {{ harvester_management_url }}"

